### ISSUE TITLE
[Bug] changing window size crashes the game

### ISSUE THREAD

**Issue by vardenixxxas** [Lyzev/Schizoid#125]
### Describe the bug

Using liquidbounce and schizoid, with the latest release works, but  one major issue is that when i try to maximise the screen (not going fullscreen) it crashes the game, im using liquidlauncher and i add schizoid as a additional mod with the latest liquidbounce nightly release

Removed the big text so it wouldnt clutter up, logs in the comments

### Steps to reproduce

```bash
1. have liquidlauncher (https://liquidbounce.net/download)

2. add latest dev build of schizoid as a additional mod in liquidlauncher https://prnt.sc/higWF-_KPWh5

3. select "show nightly builds" and for "build" select "latest" https://prnt.sc/rFCZXg6fztqU

4. Launch liquidbounce and if needed it will download it

5. when its launched, try to maximize the screen
```

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by vardenixxxas** [comment]
i must not know how logs work but i hope for a fix 🙏

**Comment by vardenixxxas** [comment]
Liquidlauncher is not uploading full log, i will try using minecraft launcher for this instead

**Comment by vardenixxxas** [comment]
https://paste.ccbluex.net/4f666e503 Minecraft launcher full log

**Comment by Lyzev** [comment]
> https://paste.ccbluex.net/4f666e503 Minecraft launcher full log

Can you provide this log file: C:\Users\varde\curseforge\minecraft\Instances\lbschizo\hs_err_pid19800.log

**Comment by Lyzev** [comment]
Did this happen once or always when starting the client?

**Comment by vardenixxxas** [comment]
> Did this happen once or always when starting the client?

i dont really understand by what you meant, but i only changed the resolution when liquidbounce loaded and that crashes always

**Comment by vardenixxxas** [comment]
[hs_err_pid19800.log](https://github.com/user-attachments/files/15748781/hs_err_pid19800.log)

> Can you provide this log file: C:\Users\varde\curseforge\minecraft\Instances\lbschizo\hs_err_pid19800.log
> 
> Otherwhise it will not be possible to find the issue

**Comment by Lyzev** [comment]
let me know if it works, this is the fixed version: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2Bac18195

**Comment by vardenixxxas** [comment]
> let me know if it works, this is the fixed version: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2Bac18195

trying it out now

**Comment by vardenixxxas** [comment]
> let me know if it works, this is the fixed version: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2Bac18195

works perfectly, only issue is that the cursor doesnt show as it should and i dont know how to screenshot cursors
