### ISSUE TITLE
[Bug] Cursor doesnt show correctly using liquidbounce with schizoid

### ISSUE THREAD

**Issue by vardenixxxas** [Lyzev/Schizoid#127]
### Describe the bug

how it looks without schizoid - https://prnt.sc/rdEFzka7A32_

how it looks with schizoid - https://prnt.sc/fUCUV7xjPMLE

### Steps to reproduce

```bash
use schizoid with liquidbounce and go into multiplayer add a server and do like the images
```

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
![image](https://github.com/Lyzev/Schizoid/assets/69327579/ef8a0c91-a183-4e83-89a5-db8efff877ad)

can you provide a valid screenshot, please

**Comment by vardenixxxas** [comment]
> 
> can you provide a valid screenshot, please

aw sorry

**Comment by vardenixxxas** [comment]
With schizoid

![image](https://github.com/Lyzev/Schizoid/assets/68706727/44fa791a-6693-4606-92df-99158db0be18)

without schizoid (ignore the background change, its a theme, not related to cursor issue)

![image](https://github.com/Lyzev/Schizoid/assets/68706727/4bcc193e-a131-423d-8ca7-b303771d7dbc)

**Comment by vardenixxxas** [comment]
🤦i forgot

**Comment by Lyzev** [comment]
should be fixed in the latest release: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B27733bc

**Comment by vardenixxxas** [comment]
> should be fixed in the latest release: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B27733bc

works, thank you, but one more last bug report incoming
