### ISSUE TITLE
[Bug] opening up schizoid clickgui crashes the game when using liquidbounce with schizoid

### ISSUE THREAD

**Issue by vardenixxxas** [Lyzev/Schizoid#131]
### Describe the bug

title

crash log

[hs_err_pid19184.log](https://github.com/user-attachments/files/15749287/hs_err_pid19184.log)

### Steps to reproduce

```bash
title  but it either crashes from the first try or 2nd or more (usually 1st or 2nd)
```

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by vardenixxxas** [comment]
i hope this bug will be the last one of 3

**Comment by Lyzev** [comment]
which schizoid version are you using?

**Comment by vardenixxxas** [comment]
> which schizoid version are you using?

latest dev build

**Comment by Lyzev** [comment]
so, [v0.1.0+07c4c71](https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B07c4c71)?

**Comment by vardenixxxas** [comment]
> so, [v0.1.0+07c4c71](https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B07c4c71)?

correct

**Comment by Lyzev** [comment]
which gpu do you use?

**Comment by vardenixxxas** [comment]
> which gpu do you use?

amd rx 6600xt

**Comment by Lyzev** [comment]
Can you try this version: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B6d07759

If it doesnt work, let me know here and I will reopen this issue.

**Comment by vardenixxxas** [comment]
> Can you try this version: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B6d07759
> 
> If it doesnt work, let me know here and I will reopen this issue.

still crashes sadly

**Comment by vardenixxxas** [comment]
[hs_err_pid19632.log](https://github.com/user-attachments/files/15749365/hs_err_pid19632.log)
crash log

**Comment by Lyzev** [comment]
i am currently trying a new way to generate the random pixels for game of life

**Comment by Lyzev** [comment]
i hope this version works: https://github.com/Lyzev/Schizoid/releases/tag/v0.1.0%2B7847679

**Comment by vardenixxxas** [comment]
works perfectly now, thank you for fixing ❤️❤️❤️
