### ISSUE TITLE
[Bug] MacOS various crashes

### ISSUE THREAD

**Issue by cranci1** [Lyzev/Schizoid#134]
### Describe the bug

Every time I open the GUI of schizoid, the client crashes. This crash also happens when I try to access the keybinds, video settings, or any settings page besides the default settings page. (should be some shader error)

https://github.com/Lyzev/Schizoid/assets/100066266/33c7ceb5-b720-4943-ab49-7f92b60495a0

log file:
[latest.log](https://github.com/user-attachments/files/15753911/latest.log)

### Steps to reproduce

```bash
GUI crash:

Just launch the game,
Enter a word/server,
Press r-shift to open the GUI, scroll with the mouse,
Game crashes.

Settings page crash:

Just launch the game,
Enter any settings page
Game crashes.
```

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by vardenixxxas** [comment]
hey, im not the dev but can you send the crash log instead of the Log file, the crash logg looks like "hs_err_pidXXXXXX"
its usually located in the minecraft installation folder

**Comment by Redstonecrafter0** [comment]
Thanks for the bug report. Can you please provide more details about your system? In particular the OpenGL version would be important.

**Comment by cranci1** [comment]
> hey, im not the dev but can you send the crash log instead of the Log file, the crash logg looks like "hs_err_pidXXXXXX" its usually located in the minecraft installation folder

Yeah the thing is that there is not hs_err_pidXXXXXX of today thats why i shared the latest.log

**Comment by cranci1** [comment]
> Thanks for the bug report. Can you please provide more details about your system? In particular the OpenGL version would be important.

OpenGL Version: 2.1 NVIDIA-16.0.13 (May have to upgrade it 💀)

**Comment by Redstonecrafter0** [comment]
Compute shaders are only supported since OpenGL 4.3. ImGUI uses the shader version 130 which is OpenGL 3.0. Your system is sadly too old to be supported.

I have seen a Linux drive on your desktop. If there is a driver for your system on Linux that supports newer OpenGL versions this might be a workaround.

As of MacOS, Apple has deprecated OpenGL in favor of Metal which is not used by Minecraft.

**Comment by cranci1** [comment]
Kinda sad but thanks guys for the help

**Comment by Lyzev** [comment]
You can try updating your system or using a different OS. I believe this issue can be closed for now.
