### ISSUE TITLE
[Bug] schizoid not launching properly

### ISSUE THREAD

**Issue by larryngton** [Lyzev/Schizoid#135]
### Describe the bug

the client doesn't launch at all, although it does show up on my mod menu

### Steps to reproduce

```bash
install arch linux (btw) and just launch the client
```

### Operating System

Linux

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
Can you provide logs or screenshot, please?

**Comment by vardenixxxas** [comment]
My guess: it cant or doesnt create a folder for schizoid and doesnt load because of that

**Comment by Lyzev** [comment]
Looks like a error in the theme detection system, I will fix it asap.
