### ISSUE TITLE
[Bug] Support another platform than Windows

### ISSUE THREAD

**Issue by Redstonecrafter0** [Lyzev/Schizoid#28]
### Describe the bug

The particle shader tries to get the screen size using win32 api which does only exist on windows.

A fix could be to use Java functionality:
```java
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
double width = screenSize.getWidth();
double height = screenSize.getHeight();
```

### Steps to reproduce

```bash
Start the client on an other platform than windows
```

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lyzev** [comment]
Could you please provide the log file.

**Comment by Redstonecrafter0** [comment]
Tested it right now. It does not crash but it also does nothing when trying to open the gui (right shift). There are no logs related to this.
